import type { Project } from '../types/project';

// Order follows the profile's positioning rule: frontend work first,
// fullstack/backend work as an ownership bonus, never the headline.
export const projects: Project[] = [
  {
    slug: 'cinestar',
    name: 'Cinestar',
    kind: 'Cinema booking',
    what: 'Online movie-ticket booking: transaction-heavy, real-time, many people booking at once.',
    role: 'Frontend Lead',
    period: '12/2023 – 04/2024',
    stack: ['Next.js', 'TypeScript', 'GraphQL'],
    url: 'https://cinestar.com.vn/',
    featured: true,
    points: [
      'Built the core booking and seat-selection flow: complex state, payment integration and real-time seat locking.',
      'Added error handling, retry flows and load-time optimisation for a more reliable checkout.',
      'Guided the team through listings, showtimes and promotions, and reviewed every PR.',
    ],
  },
  {
    slug: 'bachlong',
    name: 'Bachlong Mobile',
    kind: 'E-commerce',
    what: 'Large mobile and electronics store serving thousands of daily active users.',
    role: 'Frontend Lead',
    period: '06/2024 – 11/2024',
    stack: ['Next.js', 'TypeScript', 'GraphQL', 'TanStack Query'],
    url: 'https://bachlongmobile.com/',
    featured: true,
    points: [
      'Planned the build, chose the stack (Next.js + TanStack Query) and reviewed all code.',
      'Delivered catalog, search and checkout with strong SEO and Lighthouse performance.',
    ],
  },
  {
    slug: 'khanhhung',
    name: 'Khanh Hung Academy',
    kind: 'E-learning',
    what: 'End-to-end platform for selling and delivering online courses.',
    role: 'Frontend Lead',
    period: '02/2024 – Present',
    stack: ['Next.js', 'TypeScript', 'GraphQL', 'GSAP', 'Socket.IO'],
    url: 'https://khanhhung.academy/learn/',
    featured: true,
    points: [
      'Built the learner site and the admin dashboard, with real-time notifications over Socket.IO.',
      'Serves 100+ active users and has been sold to 100+ paying customers.',
    ],
  },
  {
    slug: 'pharceco',
    name: 'Nhà thuốc Pharceco',
    kind: 'Online pharmacy',
    what: 'Multi-branch pharmacy store with complex categories and prescription handling.',
    role: 'Frontend Lead',
    period: '11/2025 – 04/2026',
    stack: ['Next.js', 'TypeScript', 'GraphQL', 'OpenAI'],
    url: 'https://nhathuocpharceco.com.vn/',
    points: [
      'Proposed the architecture and stack, led the team and reviewed its code.',
      'Built catalog, prescription upload and checkout, pixel-perfect from Figma.',
      'Added AI to search with OpenAI and Google Speech-to-Text.',
    ],
  },
  {
    slug: 'nhahang',
    name: 'NHAHANG.AI',
    kind: 'Restaurant SaaS',
    what: 'Restaurant-management SaaS: POS, dine-in and takeaway ordering, promotions, payments and reports.',
    role: 'Fullstack Developer, also PM and QA',
    period: '04/2026 – Present',
    stack: ['Next.js', 'C# / .NET', 'SQL Server', 'Redis'],
    url: 'https://nhahang.ai/',
    note: 'End-to-end ownership',
    points: [
      'Took over a production system from another team and now maintain it alone; 20 restaurants use it daily.',
      'Made the order-list query about 50% faster.',
      'Redesigned automatic payments so each restaurant links its own SePay account, cutting running costs.',
      'Added an in-app AI assistant with a RAG pipeline that customers can feed with their own knowledge.',
    ],
  },
  {
    slug: 'skillhub',
    name: 'Mona Skillhub',
    kind: 'Internal learning',
    what: 'Teaching and self-learning platform with real-time features and a full admin.',
    role: 'Frontend Lead',
    period: '03/2025 – 06/2025',
    stack: ['Next.js', 'TypeScript', 'GraphQL', 'GSAP', 'Socket.IO'],
    url: 'https://skillhub.mona.academy/',
    points: ['Led the admin dashboard for content and user management.', 'Defined the UI architecture and built the GSAP transitions and animations.'],
  },
  {
    slug: 'hydrashop',
    name: 'Hydrashop',
    kind: 'Fashion e-commerce',
    what: 'Minimal, high-performance fashion store by Hydra Studio.',
    role: 'Frontend Lead',
    period: '09/2025 – 01/2026',
    stack: ['Next.js', 'TypeScript', 'GraphQL'],
    url: 'https://hydrashop.vn/',
    points: ['Allocated tasks, tracked progress, reviewed code and proposed technical solutions.', 'Built the catalog, cart and checkout flows.'],
  },
  {
    slug: 'kimthanh',
    name: 'Kim Thanh',
    kind: 'Motorbike parts store',
    what: 'Genuine Honda, Yamaha, SYM, Suzuki and Piaggio parts, wholesale and retail.',
    role: 'Frontend Lead',
    period: '04/2024 – 07/2024',
    stack: ['Next.js', 'TypeScript', 'GraphQL'],
    url: 'https://kimthanh.com.vn/',
    points: [
      'Took the team from kickoff to release: component architecture, stack, code review and mentoring.',
      'Delivered landing and product-detail pages with optimised SEO and performance.',
    ],
  },
  {
    slug: 'thienquan',
    name: 'BĐS Thiên Quân',
    kind: 'Real-estate listings',
    what: 'Listing platform with wallet top-up, posting packages and boosted listings.',
    role: 'Team Lead, team of 4',
    period: '05/2026 – 07/2026',
    stack: ['Next.js', 'Golang (familiar, AI-assisted)'],
    status: 'Not launched yet',
    points: [
      'Led a team of 4, with 2 direct reports.',
      'Built the CMS, blog and policy modules and supported the admin dashboard.',
      'Contributed to wallet top-up, posting packages, listing boosts and user management.',
    ],
  },
];
