import { Bot, GraduationCap, LayoutDashboard, ShoppingBag, type LucideIcon } from 'lucide-react';
import type { Project, ProjectCategory } from '../types/project';

/** Sections of the /work page, in display order. The icon fills a card that has no screenshot. */
export const categories: { id: ProjectCategory; title: string; blurb: string; icon: LucideIcon }[] = [
  { id: 'store', title: 'Storefronts', blurb: 'E-commerce and booking sites, mostly Next.js on a GraphQL backend.', icon: ShoppingBag },
  { id: 'learning', title: 'Learning platforms', blurb: 'Course sales, learning sites and the dashboards that run them.', icon: GraduationCap },
  { id: 'saas', title: 'SaaS, ERP and back offices', blurb: 'Products people log in to every day.', icon: LayoutDashboard },
  { id: 'ai', title: 'AI and automation', blurb: 'MCP servers and bots that let AI assistants work with these products.', icon: Bot },
];

// Projects with `points` come from master-profile.md and also appear on the résumé. Order follows the
// profile's positioning rule: frontend work first, fullstack/backend work as an ownership bonus.
// The rest come from the git history in ~/Desktop/Mona: period = Nhật's first to last commit, no role claimed.
export const projects: Project[] = [
  {
    slug: 'cinestar',
    name: 'Cinestar',
    category: 'store',
    kind: 'Cinema booking',
    what: 'Online movie-ticket booking: transaction-heavy, real-time, many people booking at once.',
    role: 'Senior Frontend Developer',
    period: '12/2023 – 04/2024',
    stack: ['Next.js', 'TypeScript', 'GraphQL'],
    url: 'https://cinestar.com.vn/',
    featured: true,
    points: [
      'Built the core booking and seat-selection flow: complex state, payment integration and real-time seat locking.',
      'Added error handling, retry flows and load-time optimisation for a more reliable checkout.',
      'Guided the team through listings, showtimes and promotions, and reviewed every PR.',
    ],
  },
  {
    slug: 'bachlong',
    name: 'Bachlong Mobile',
    category: 'store',
    kind: 'E-commerce',
    what: 'Large mobile and electronics store serving thousands of daily active users.',
    role: 'Senior Frontend Developer',
    period: '06/2024 – 11/2024',
    stack: ['Next.js', 'TypeScript', 'GraphQL', 'TanStack Query'],
    url: 'https://bachlongmobile.com/',
    featured: true,
    points: [
      'Planned the build, chose the stack (Next.js + TanStack Query) and reviewed all code.',
      'Delivered catalog, search and checkout with strong SEO and Lighthouse performance.',
    ],
  },
  {
    slug: 'khanhhung',
    name: 'Khanh Hung Academy',
    category: 'learning',
    kind: 'E-learning',
    what: 'End-to-end platform for selling and delivering online courses.',
    role: 'Senior Frontend Developer',
    period: '02/2024 – Present',
    stack: ['Next.js', 'TypeScript', 'GraphQL', 'GSAP', 'Socket.IO'],
    url: 'https://khanhhung.academy/learn/',
    featured: true,
    points: [
      'Built the learner site and the admin dashboard, with real-time notifications over Socket.IO.',
      'Serves 100+ active users and has been sold to 100+ paying customers.',
    ],
  },
  {
    slug: 'pharceco',
    name: 'Nhà thuốc Pharceco',
    category: 'store',
    kind: 'Online pharmacy',
    what: 'Multi-branch pharmacy store with complex categories and prescription handling.',
    role: 'Senior Frontend Developer',
    period: '11/2025 – 04/2026',
    stack: ['Next.js', 'TypeScript', 'GraphQL', 'OpenAI'],
    url: 'https://nhathuocpharceco.com.vn/',
    points: [
      'Proposed the architecture and stack, led the team and reviewed its code.',
      'Built catalog, prescription upload and checkout, pixel-perfect from Figma.',
      'Added AI to search with OpenAI and Google Speech-to-Text.',
    ],
  },
  {
    slug: 'nhahang',
    name: 'NHAHANG.AI',
    category: 'saas',
    kind: 'Restaurant SaaS',
    what: 'Restaurant-management SaaS: POS, dine-in and takeaway ordering, promotions, payments and reports.',
    role: 'Fullstack Developer, also PM and QA',
    period: '04/2026 – Present',
    stack: ['Next.js', 'C# / .NET', 'SQL Server', 'Redis'],
    url: 'https://nhahang.ai/',
    note: 'End-to-end ownership',
    points: [
      'Took over a production system from another team and now maintain it alone; 20 restaurants use it daily.',
      'Made the order-list query about 50% faster.',
      'Redesigned automatic payments so each restaurant links its own SePay account, cutting running costs.',
      'Added an in-app AI assistant with a RAG pipeline that customers can feed with their own knowledge.',
    ],
  },
  {
    slug: 'skillhub',
    name: 'Mona Skillhub',
    category: 'learning',
    kind: 'Internal learning',
    what: 'Teaching and self-learning platform with real-time features and a full admin.',
    role: 'Senior Frontend Developer',
    period: '03/2025 – 06/2025',
    stack: ['Next.js', 'TypeScript', 'GraphQL', 'GSAP', 'Socket.IO'],
    url: 'https://skillhub.mona.academy/',
    points: ['Led the admin dashboard for content and user management.', 'Defined the UI architecture and built the GSAP transitions and animations.'],
  },
  {
    slug: 'hydrashop',
    name: 'Hydrashop',
    category: 'store',
    kind: 'Fashion e-commerce',
    what: 'Minimal, high-performance fashion store by Hydra Studio.',
    role: 'Senior Frontend Developer',
    period: '09/2025 – 01/2026',
    stack: ['Next.js', 'TypeScript', 'GraphQL'],
    url: 'https://hydrashop.vn/',
    points: ['Allocated tasks, tracked progress, reviewed code and proposed technical solutions.', 'Built the catalog, cart and checkout flows.'],
  },
  {
    slug: 'kimthanh',
    name: 'Kim Thanh',
    category: 'store',
    kind: 'Motorbike parts store',
    what: 'Genuine Honda, Yamaha, SYM, Suzuki and Piaggio parts, wholesale and retail.',
    role: 'Senior Frontend Developer',
    period: '04/2024 – 07/2024',
    stack: ['Next.js', 'TypeScript', 'GraphQL'],
    url: 'https://kimthanh.com.vn/',
    points: [
      'Took the team from kickoff to release: component architecture, stack, code review and mentoring.',
      'Delivered landing and product-detail pages with optimised SEO and performance.',
    ],
  },
  {
    slug: 'thienquan',
    name: 'BĐS Thiên Quân',
    category: 'saas',
    kind: 'Real-estate listings',
    what: 'Listing platform with wallet top-up, posting packages and boosted listings.',
    role: 'Senior Developer, team of 4',
    period: '05/2026 – 07/2026',
    stack: ['Next.js', 'Golang (familiar, AI-assisted)'],
    status: 'Not launched yet',
    points: [
      'Led a team of 4, with 2 direct reports.',
      'Built the CMS, blog and policy modules and supported the admin dashboard.',
      'Contributed to wallet top-up, posting packages, listing boosts and user management.',
    ],
  },

  // ---------- From the git history ----------

  {
    slug: 'inwine',
    name: 'InWine',
    category: 'store',
    kind: 'Wine store',
    what: 'Online store of a fine-wine importer, with an age gate, brand pages and a mega menu.',
    period: '11/2023 – 04/2026',
    stack: ['Next.js', 'TypeScript', 'GraphQL', 'Ant Design'],
    url: 'https://inwine.vn/',
  },
  {
    slug: 'wiisnt',
    name: 'What It Isnt',
    category: 'store',
    kind: 'Streetwear store',
    what: 'Fashion brand store with Google sign-in, wishlist and one-tap buy-again.',
    period: '11/2023 – 09/2026',
    stack: ['Next.js', 'TypeScript', 'GraphQL', 'GSAP'],
    url: 'https://wiisnt.vn/',
  },
  {
    slug: 'otpcom',
    name: 'OTPCOM',
    category: 'store',
    kind: 'Auto-parts store',
    what: 'Car-parts store with search by make and model, promotions and a blog.',
    period: '09/2023 – 07/2026',
    stack: ['Next.js', 'TypeScript', 'GraphQL'],
    url: 'https://otpcom.vn/',
  },
  {
    slug: 'sieuthinghenhin',
    name: 'Siêu Thị Nghe Nhìn',
    category: 'store',
    kind: 'Audio-visual store',
    what: 'Speakers, soundbars and home-theatre store with structured-data SEO.',
    period: '07/2024 – Present',
    stack: ['Next.js', 'TypeScript', 'GraphQL', 'TanStack Query'],
    url: 'https://sieuthinghenhin.vn/',
  },
  {
    slug: 'labee',
    name: 'Labee',
    category: 'store',
    kind: 'Lab supplies store',
    what: 'Lab chemicals and equipment store with deep category filters and news.',
    period: '06/2025 – 09/2026',
    stack: ['Next.js', 'TypeScript', 'GraphQL'],
    url: 'https://labee.vn/',
  },
  {
    slug: 'sophie',
    name: 'Sophie Distributor',
    category: 'store',
    kind: 'Nail supplies (US)',
    what: 'US nail-supply store taking card, Google Pay and Apple Pay through Square.',
    period: '02/2025 – 12/2025',
    stack: ['Next.js', 'TypeScript', 'GraphQL', 'Square'],
    status: 'Link coming soon',
  },
  {
    slug: 'retail-starter',
    name: 'Mona Retail starter',
    category: 'store',
    kind: 'Internal template',
    what: 'The Next.js starter most of these storefronts are cut from.',
    period: '04/2024 – 07/2025',
    stack: ['Next.js', 'TypeScript', 'GraphQL', 'MUI'],
    status: 'Internal template',
  },
  {
    slug: 'monaacademy',
    name: 'Mona Academy',
    category: 'learning',
    kind: 'E-learning SaaS',
    what: 'Course creators sign up and pay for their own branded learning site, one tenant each.',
    period: '11/2024 – 09/2026',
    stack: ['Next.js', 'TypeScript', 'GraphQL', 'GSAP'],
    url: 'https://mona.academy/',
  },
  {
    slug: 'community',
    name: 'Mona Community',
    category: 'learning',
    kind: 'Community platform',
    what: 'Groups, posts and chat for course communities, with single sign-on from Mona Academy.',
    period: '03/2026 – 06/2026',
    stack: ['Next.js', 'TypeScript', 'MUI', 'TanStack Query'],
    status: 'Members only',
  },
  {
    slug: 'kira',
    name: 'Kira Kể Chuyện',
    category: 'saas',
    kind: 'Kids audio app',
    what: 'Bedtime stories for children aged 2 to 6: the admin for stories, customers and subscriptions, and its API.',
    period: '06/2026 – Present',
    stack: ['React', 'Vite', 'TanStack Query', 'Go (AI-assisted)'],
    url: 'https://kirakechuyen.com/',
  },
  {
    slug: 'kimthanh-erp',
    name: 'Kim Thanh ERP',
    category: 'saas',
    kind: 'Sales and stock ERP',
    what: 'Sales, stock and coupon management for Kim Thanh, on a Magento backend.',
    period: '02/2024 – 09/2026',
    stack: ['Next.js', 'TypeScript', 'Ant Design', 'Magento'],
    status: 'Internal, behind login',
  },
  {
    slug: 'otpcom-erp',
    name: 'OTPCOM ERP',
    category: 'saas',
    kind: 'Back office',
    what: 'Products, media library, Excel import and shipping setup (GHN, GHTK) for OTPCOM.',
    period: '02/2025 – 04/2026',
    stack: ['Next.js', 'TypeScript', 'Ant Design', 'Socket.IO'],
    status: 'Internal, behind login',
  },
  {
    slug: 'spectrum',
    name: 'Spectrum Signs & Graphics',
    category: 'saas',
    kind: 'Custom decals (US)',
    what: 'Storefront with an in-browser decal designer that renders print-ready PDFs.',
    period: '09/2026 – Present',
    stack: ['Next.js', 'TypeScript', 'Go (AI-assisted)'],
    status: 'In development',
  },
  {
    slug: 'kimlongtai',
    name: 'Kim Long Tài JMS',
    category: 'saas',
    kind: 'Jewellery management',
    what: 'Inventory, import and order management for a gold and jewellery retailer.',
    period: '08/2026 – 09/2026',
    stack: ['Next.js', 'MUI', 'ASP.NET Core'],
    status: 'In development',
  },
  {
    slug: 'academy-mcp',
    name: 'Mona Academy MCP',
    category: 'ai',
    kind: 'MCP server',
    what: 'Site owners manage their learning site, page builder included, from an AI assistant.',
    period: '07/2026 – 09/2026',
    stack: ['TypeScript', 'MCP SDK', 'Express'],
    status: 'MCP server',
  },
  {
    slug: 'skillhub-mcp',
    name: 'SkillHub MCP',
    category: 'ai',
    kind: 'MCP server',
    what: 'Opens the SkillHub LMS to AI assistants through 89 tools.',
    period: '08/2026 – 09/2026',
    stack: ['TypeScript', 'MCP SDK', 'Express'],
    status: 'MCP server',
  },
  {
    slug: 'nhahang-mcp',
    name: 'NHAHANG.AI MCP',
    category: 'ai',
    kind: 'MCP server',
    what: 'Platform-owner tools for nhahang.ai: tenant diagnostics, packages, payments and reports.',
    period: '09/2026',
    stack: ['TypeScript', 'MCP SDK', 'Express'],
    status: 'MCP server',
  },
  {
    slug: 'agentdesk',
    name: 'AgentDesk',
    category: 'ai',
    kind: 'AI support bot',
    what: 'Support bot on Zalo and Telegram with a knowledge base, incidents and Jira/GitLab automation.',
    period: '09/2026',
    stack: ['Go (AI-assisted)'],
    status: 'Lives in Zalo and Telegram',
  },
  {
    slug: 'webhook-agent',
    name: 'WP Webhook Agent',
    category: 'ai',
    kind: 'Automation agent',
    what: 'Runs headless Claude Code against WordPress and Magento sites when a webhook fires.',
    period: '09/2026',
    stack: ['Go (AI-assisted)', 'Claude Code'],
    status: 'Internal tool',
  },
];
